# Please keep AllCops, Bundler, Style, Metrics groups and then order cops
# alphabetically
inherit_from:
  - https://raw.githubusercontent.com/hanami/devtools/main/.rubocop.yml
Naming/HeredocDelimiterNaming:
  Enabled: false
Layout/LineLength:
  Exclude:
    - "lib/hanami/helpers/escape_helper.rb"
    - "lib/hanami/helpers/form_helper.rb"
    - "lib/hanami/helpers/form_helper/form_builder.rb"
    - "spec/**/*.rb"
Lint/EmptyBlock:
  Exclude:
    - "spec/unit/hanami/helpers/form_helper_spec.rb"
